services:
  app:
    entrypoint:
      - sleep
      - infinity
    environment:
      - ABOUT=WebAssembly with Go and TinyGo
    build:         
      args:
        # Change the desired architecture: `WORKSPACE_ARCH=arm64 or amd64`
        - WORKSPACE_ARCH=arm64
        - GO_VERSION=1.21.3
        - TINYGO_VERSION=0.30.0
        - EXTISM_VERSION=0.3.3
        - NODE_MAJOR=20
        - SWIFT_VERSION=5.8.0-RELEASE
        # ubuntu20.04_x86_64 ubuntu20.04_aarch64
        - SWIFT_ARCH=ubuntu20.04_aarch64
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ~/.ssh:/root/.ssh # be careful to the user
      #- ~/.ssh:/k33g_org/.ssh # be careful to the user
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

